# Generated by Django 5.2 on 2025-04-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='reader_contact',
            field=models.CharField(max_length=10),
        ),
    ]
