# Generated by Django 5.2 on 2025-04-30 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0003_book_issuedbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='reader_contact',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Contact number must be a 10-digit number', regex='^\\d{10}$')]),
        ),
    ]
