# Generated by Django 5.2 on 2025-04-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0004_alter_reader_reader_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedbook',
            name='allowed_days',
            field=models.IntegerField(default=15),
        ),
    ]
